version: "3.6"
services:
    db:
        image: postgres
        volumes:
            - ./docker/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=stock
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
